# Generated by Django 3.2.9 on 2021-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_category_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='blog.Post'),
        ),
    ]
