# Generated by Django 3.2.9 on 2021-11-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('accounts', '0003_auto_20211110_1758'),
        ('orders', '0002_auto_20211110_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='card.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_customer', to='accounts.customer'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
